version: '3'

services:
        
        consul:
                image: consul
                restart: unless-stopped
                command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
                ports:
                - 0.0.0.0:8500:8500
                - 0.0.0.0:8600:8600/udp
                networks:
                - workshop
        
        rng:
                build: 
                        context: ./rng
                        dockerfile: dockerfile
                ports: 
                - 9001:80
                networks:
                - workshop
                environment:
                - SRVRNGPORT=${SRVRNGPORT}
                depends_on:
                - consul

        hasher:
                build: 
                        context: ./hasher
                        dockerfile: dockerfile
                ports:
                - 9002:80
                networks:
                - workshop
                environment:
                - SRVHASHERPORT=${SRVHASHERPORT}
                depends_on:
                - rng

        worker:
                build: 
                        context: ./worker
                        dockerfile: dockerfile
                networks:
                - workshop
                environment:
                - SRVRNGPORT=${SRVRNGPORT}
                - SRVHASHERPORT=${SRVHASHERPORT}
                - SRVHASHERNAME=${SRVHASHERNAME}
                - SRVRNGNAME=${SRVRNGNAME}
                depends_on:
                - hasher

        webui:
                build: 
                        context: ./webui
                        dockerfile: dockerfile
                ports:
                - 8000:80
                networks:
                - workshop
                volumes:
                        - "./webui/files/:/files/"
                
        redis:
                image: redis:latest
                networks:
                - workshop

networks:
                workshop:





